### ISSUE TITLE
Roblox API

### ISSUE THREAD

**Issue by sbhadr** [gamenew09/RobloxAPI#1]
I saw that you created a Roblox API library in C#. I want to get in touch with you. 

I couldn't express much of what I wanted to say in this short body. Please have a look at [this](https://forum.roblox.com/Forum/ShowPost.aspx?PostID=221414751) for more information.

The link is a roblox forum link. If you don't like forums, I'd be happy to explain further here.
Hope to hear your response soon! :)

**Comment by gamenew09** [comment]
I have joined the discord. Closing this issue now.
